"""orm_schema_from_models

Revision ID: df2496c74ef0
Revises: 71c04a590a2b
Create Date: 2026-04-08 07:52:34.191993

Full schema from ORM models. Use on an empty database: ``alembic upgrade head``.

If tables already exist (e.g. from ``create_all``), either ``alembic stamp
df2496c74ef0`` when the live schema matches this revision, or drop/recreate
(``scripts/recreate_schema.py``) then run migrations.

Autogenerated against SQLite; ``sqlite.JSON`` was replaced with ``sa.JSON`` for
MySQL/Postgres compatibility. Timestamp defaults use ``CURRENT_TIMESTAMP``.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'df2496c74ef0'
down_revision: Union[str, Sequence[str], None] = '71c04a590a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('address_type', sa.String(length=255), nullable=True),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_addresses_client', 'addresses', ['client_id', 'is_default', 'is_active'], unique=False)
    op.create_index('idx_addresses_type', 'addresses', ['client_id', 'address_type'], unique=False)
    op.create_index(op.f('ix_addresses_client_id'), 'addresses', ['client_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_radius_km', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_areas_active', 'areas', ['is_active'], unique=False)
    op.create_index('idx_areas_code', 'areas', ['code'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_target', 'audit_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('batch_meals',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_meals_batch', 'batch_meals', ['batch_id', 'status'], unique=False)
    op.create_index('idx_batch_meals_order', 'batch_meals', ['order_id'], unique=False)
    op.create_index('idx_batch_meals_unique', 'batch_meals', ['batch_id', 'order_id'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('area_id', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=255), nullable=False),
    sa.Column('timeslot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeslot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('delivery_agent_id', sa.String(length=255), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('packed_count', sa.Integer(), nullable=True),
    sa.Column('ready_count', sa.Integer(), nullable=True),
    sa.Column('picked_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batches_agent', 'batches', ['delivery_agent_id', 'status'], unique=False)
    op.create_index('idx_batches_area_meal', 'batches', ['area_id', 'meal_type', 'timeslot_start'], unique=False)
    op.create_index('idx_batches_status', 'batches', ['status', 'created_at'], unique=False)
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blacklisted_token_expires', 'blacklisted_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_blacklisted_tokens_expires_at'), 'blacklisted_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_blacklisted_tokens_token'), 'blacklisted_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_blacklisted_tokens_token_hash'), 'blacklisted_tokens', ['token_hash'], unique=True)
    op.create_table('checkout_data',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('meal_plan_id', sa.String(length=255), nullable=False),
    sa.Column('plan_category', sa.String(length=255), nullable=False),
    sa.Column('health_inputs', sa.Text(), nullable=True),
    sa.Column('meal_timing', sa.Text(), nullable=True),
    sa.Column('consultation_preference', sa.Boolean(), nullable=True),
    sa.Column('consultation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_time_slot', sa.String(length=255), nullable=True),
    sa.Column('consultation_mode', sa.String(length=255), nullable=True),
    sa.Column('delivery_addresses', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkout_plan', 'checkout_data', ['meal_plan_id', 'status'], unique=False)
    op.create_index('idx_checkout_subscription', 'checkout_data', ['subscription_id'], unique=False)
    op.create_index('idx_checkout_user_status', 'checkout_data', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_checkout_data_meal_plan_id'), 'checkout_data', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_checkout_data_subscription_id'), 'checkout_data', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_checkout_data_user_id'), 'checkout_data', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('nutritionist_id', sa.String(length=255), nullable=True),
    sa.Column('weight_start', sa.Float(), nullable=True),
    sa.Column('weight_current', sa.Float(), nullable=True),
    sa.Column('weight_goal', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('health_conditions', sa.Text(), nullable=True),
    sa.Column('dietary_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_nutritionist', 'clients', ['nutritionist_id'], unique=False)
    op.create_index('idx_clients_user', 'clients', ['user_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('nutritionist_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_slot', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consultations_client_date', 'consultations', ['client_id', 'date', 'status'], unique=False)
    op.create_index('idx_consultations_nutritionist_date', 'consultations', ['nutritionist_id', 'date', 'status'], unique=False)
    op.create_table('daily_meal_schedules',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breakfast_item', sa.String(length=255), nullable=True),
    sa.Column('breakfast_calories', sa.Integer(), nullable=True),
    sa.Column('breakfast_status', sa.String(length=255), nullable=True),
    sa.Column('lunch_item', sa.String(length=255), nullable=True),
    sa.Column('lunch_calories', sa.Integer(), nullable=True),
    sa.Column('lunch_status', sa.String(length=255), nullable=True),
    sa.Column('dinner_item', sa.String(length=255), nullable=True),
    sa.Column('dinner_calories', sa.Integer(), nullable=True),
    sa.Column('dinner_status', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_nutritionist_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_meals_client_date', 'daily_meal_schedules', ['client_id', 'date', 'created_at'], unique=False)
    op.create_index('idx_daily_meals_subscription_date', 'daily_meal_schedules', ['subscription_id', 'date', 'created_at'], unique=False)
    op.create_table('delivery_agents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=255), nullable=False),
    sa.Column('vehicle_number', sa.String(length=255), nullable=True),
    sa.Column('current_latitude', sa.String(length=255), nullable=True),
    sa.Column('current_longitude', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('areas_served', sa.Text(), nullable=True),
    sa.Column('current_batch_id', sa.String(length=255), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_agents_available', 'delivery_agents', ['is_available', 'is_online'], unique=False)
    op.create_index('idx_delivery_agents_batch', 'delivery_agents', ['current_batch_id'], unique=False)
    op.create_table('delivery_tracking',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('delivery_agent_id', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.String(length=255), nullable=False),
    sa.Column('destination_latitude', sa.String(length=255), nullable=True),
    sa.Column('destination_longitude', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_data', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_agent', 'delivery_tracking', ['delivery_agent_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_delivery_order', 'delivery_tracking', ['order_id', 'status', 'created_at'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('app_version', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_tokens_token', 'device_tokens', ['token', 'is_active'], unique=False)
    op.create_index('idx_device_tokens_user_platform', 'device_tokens', ['user_id', 'platform', 'is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_is_active'), 'device_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_platform'), 'device_tokens', ['platform'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('aggregate_type', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_aggregate', 'events', ['aggregate_type', 'aggregate_id', 'created_at'], unique=False)
    op.create_index('idx_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_aggregate_id'), 'events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_events_aggregate_type'), 'events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('kitchen_queue',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('meal_name', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=255), nullable=False),
    sa.Column('diet_plan', sa.String(length=255), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('chef_assigned', sa.String(length=255), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_plans_active', 'meal_plans', ['is_active'], unique=False)
    op.create_index('idx_meal_plans_category_active', 'meal_plans', ['category', 'is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('delivery_provider', sa.String(length=255), nullable=True),
    sa.Column('delivery_provider_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_channel', 'notifications', ['channel', 'status', 'created_at'], unique=False)
    op.create_index('idx_notifications_user_status', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('nutritionists',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('total_clients', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('available_slots', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_nutritionists_available', 'nutritionists', ['is_available'], unique=False)
    op.create_index('idx_nutritionists_rating', 'nutritionists', ['rating'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('daily_meal_schedule_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=255), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=False),
    sa.Column('diet_plan', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('kitchen_status', sa.String(length=255), nullable=True),
    sa.Column('delivery_agent_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_agent_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.Column('consumed_status', sa.String(length=255), nullable=True),
    sa.Column('consumption_logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=255), nullable=True),
    sa.Column('timeslot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeslot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_printed', sa.Boolean(), nullable=True),
    sa.Column('label_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_orders_agent', 'orders', ['delivery_agent_id', 'status'], unique=False)
    op.create_index('idx_orders_area_batch', 'orders', ['area_id', 'batch_id', 'meal_type'], unique=False)
    op.create_index('idx_orders_client_status', 'orders', ['client_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_orders_idempotency', 'orders', ['idempotency_key'], unique=False)
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_orders_timeslot', 'orders', ['timeslot_start', 'timeslot_end'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=False),
    sa.Column('payment_provider', sa.String(length=255), nullable=True),
    sa.Column('payment_provider_id', sa.String(length=255), nullable=True),
    sa.Column('payment_provider_reference', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_client_status', 'payments', ['client_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_payments_order', 'payments', ['order_id', 'status'], unique=False)
    op.create_index('idx_payments_subscription', 'payments', ['subscription_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_provider_id'), 'payments', ['payment_provider_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_benefit', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('nutritional_highlights', sa.JSON(), nullable=True),
    sa.Column('key_benefits', sa.JSON(), nullable=True),
    sa.Column('suitable_for', sa.JSON(), nullable=True),
    sa.Column('nutritionist_endorsements', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_active', 'products', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_products_category', 'products', ['category', 'is_active'], unique=False)
    op.create_index('idx_products_featured', 'products', ['is_featured', 'is_active'], unique=False)
    op.create_table('progress_logs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('calories_consumed', sa.Integer(), nullable=True),
    sa.Column('protein_intake', sa.Float(), nullable=True),
    sa.Column('water_intake_liters', sa.Float(), nullable=True),
    sa.Column('meal_completion_percent', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_client_date', 'progress_logs', ['client_id', 'log_date', 'created_at'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_method', sa.String(length=255), nullable=True),
    sa.Column('payment_provider_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('refund_metadata', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refunds_client', 'refunds', ['client_id', 'created_at'], unique=False)
    op.create_index('idx_refunds_payment', 'refunds', ['payment_id', 'status'], unique=False)
    op.create_index(op.f('ix_refunds_client_id'), 'refunds', ['client_id'], unique=False)
    op.create_index(op.f('ix_refunds_idempotency_key'), 'refunds', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('ix_refunds_subscription_id'), 'refunds', ['subscription_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('nutritionist_id', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('nutritionist_id', sa.String(length=255), nullable=True),
    sa.Column('meal_plan_id', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('allocation_status', sa.String(length=255), nullable=True),
    sa.Column('checkout_data_id', sa.String(length=255), nullable=True),
    sa.Column('health_inputs', sa.Text(), nullable=True),
    sa.Column('meal_timing', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_allocation', 'subscriptions', ['allocation_status', 'created_at'], unique=False)
    op.create_index('idx_subscriptions_client_status', 'subscriptions', ['client_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_subscriptions_nutritionist', 'subscriptions', ['nutritionist_id', 'status'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('nutritionist_id', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=255), nullable=False),
    sa.Column('activity_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activities_nutritionist', 'user_activities', ['nutritionist_id', 'created_at'], unique=False)
    op.create_index('idx_user_activities_subscription', 'user_activities', ['subscription_id', 'created_at'], unique=False)
    op.create_index('idx_user_activities_type', 'user_activities', ['activity_type', 'created_at'], unique=False)
    op.create_index('idx_user_activities_user_date', 'user_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_nutritionist_id'), 'user_activities', ['nutritionist_id'], unique=False)
    op.create_index(op.f('ix_user_activities_subscription_id'), 'user_activities', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_reports',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('total_meals_delivered', sa.Integer(), nullable=True),
    sa.Column('meals_consumed', sa.Integer(), nullable=True),
    sa.Column('meals_skipped', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('avg_calories_per_day', sa.Integer(), nullable=True),
    sa.Column('weight_change', sa.Float(), nullable=True),
    sa.Column('nutritionist_notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_client_generated', 'weekly_reports', ['client_id', 'generated_at'], unique=False)
    op.create_index('idx_reports_client_subscription', 'weekly_reports', ['client_id', 'subscription_id', 'week_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_client_subscription', table_name='weekly_reports')
    op.drop_index('idx_reports_client_generated', table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_subscription_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_nutritionist_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_index('idx_user_activities_user_date', table_name='user_activities')
    op.drop_index('idx_user_activities_type', table_name='user_activities')
    op.drop_index('idx_user_activities_subscription', table_name='user_activities')
    op.drop_index('idx_user_activities_nutritionist', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index('idx_subscriptions_nutritionist', table_name='subscriptions')
    op.drop_index('idx_subscriptions_client_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_allocation', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refunds_subscription_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_idempotency_key'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_client_id'), table_name='refunds')
    op.drop_index('idx_refunds_payment', table_name='refunds')
    op.drop_index('idx_refunds_client', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('idx_progress_client_date', table_name='progress_logs')
    op.drop_table('progress_logs')
    op.drop_index('idx_products_featured', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_active', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_provider_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index('idx_payments_subscription', table_name='payments')
    op.drop_index('idx_payments_order', table_name='payments')
    op.drop_index('idx_payments_client_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_orders_timeslot', table_name='orders')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_index('idx_orders_idempotency', table_name='orders')
    op.drop_index('idx_orders_client_status', table_name='orders')
    op.drop_index('idx_orders_area_batch', table_name='orders')
    op.drop_index('idx_orders_agent', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_nutritionists_rating', table_name='nutritionists')
    op.drop_index('idx_nutritionists_available', table_name='nutritionists')
    op.drop_table('nutritionists')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notifications_user_status', table_name='notifications')
    op.drop_index('idx_notifications_channel', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_meal_plans_category_active', table_name='meal_plans')
    op.drop_index('idx_meal_plans_active', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_table('kitchen_queue')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_type'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_id'), table_name='events')
    op.drop_index('idx_events_type_created', table_name='events')
    op.drop_index('idx_events_aggregate', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_platform'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_is_active'), table_name='device_tokens')
    op.drop_index('idx_device_tokens_user_platform', table_name='device_tokens')
    op.drop_index('idx_device_tokens_token', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('idx_delivery_order', table_name='delivery_tracking')
    op.drop_index('idx_delivery_agent', table_name='delivery_tracking')
    op.drop_table('delivery_tracking')
    op.drop_index('idx_delivery_agents_batch', table_name='delivery_agents')
    op.drop_index('idx_delivery_agents_available', table_name='delivery_agents')
    op.drop_table('delivery_agents')
    op.drop_index('idx_daily_meals_subscription_date', table_name='daily_meal_schedules')
    op.drop_index('idx_daily_meals_client_date', table_name='daily_meal_schedules')
    op.drop_table('daily_meal_schedules')
    op.drop_index('idx_consultations_nutritionist_date', table_name='consultations')
    op.drop_index('idx_consultations_client_date', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('idx_clients_user', table_name='clients')
    op.drop_index('idx_clients_nutritionist', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_checkout_data_user_id'), table_name='checkout_data')
    op.drop_index(op.f('ix_checkout_data_subscription_id'), table_name='checkout_data')
    op.drop_index(op.f('ix_checkout_data_meal_plan_id'), table_name='checkout_data')
    op.drop_index('idx_checkout_user_status', table_name='checkout_data')
    op.drop_index('idx_checkout_subscription', table_name='checkout_data')
    op.drop_index('idx_checkout_plan', table_name='checkout_data')
    op.drop_table('checkout_data')
    op.drop_index(op.f('ix_blacklisted_tokens_token_hash'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_blacklisted_tokens_token'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_blacklisted_tokens_expires_at'), table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_token_expires', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    op.drop_index('idx_batches_status', table_name='batches')
    op.drop_index('idx_batches_area_meal', table_name='batches')
    op.drop_index('idx_batches_agent', table_name='batches')
    op.drop_table('batches')
    op.drop_index('idx_batch_meals_unique', table_name='batch_meals')
    op.drop_index('idx_batch_meals_order', table_name='batch_meals')
    op.drop_index('idx_batch_meals_batch', table_name='batch_meals')
    op.drop_table('batch_meals')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_target', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_areas_code', table_name='areas')
    op.drop_index('idx_areas_active', table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_addresses_client_id'), table_name='addresses')
    op.drop_index('idx_addresses_type', table_name='addresses')
    op.drop_index('idx_addresses_client', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
